// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

function readEnv(name: string): string | undefined {
  const value = process.env[name]?.trim();
  return value ? value : undefined;
}

const migrationDatabaseUrl =
  readEnv("POSTGRES_URL_NON_POOLING") ??
  readEnv("DATABASE_URL") ??
  readEnv("POSTGRES_URL") ??
  readEnv("POSTGRES_PRISMA_URL");

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: migrationDatabaseUrl,
  },
});
